jQuery(document).ready(function($){
  $("a").eq(0).click(function(){
		$($("#m1")[0]).prependTo($('.cont'));
  });
  $("a").eq(1).click(function(){
  	$($("#m2")[0]).prependTo($('.cont'));
  });
  $("a").eq(2).click(function(){
  		$($("#m3")[0]).prependTo($('.cont'));
  });
	$("a").eq(3).click(function(){
  $($("#m4")[0]).prependTo($('.cont'));
});
	$("a").eq(4).click(function(){
  $($("#m5")[0]).prependTo($('.cont'));
});
})